---
name: openvpn

releases:
- name: bpm
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
  version: 0.2.0
- name: openvpn
  sha1: 1b77cbd51a3debefcb06f2ad5311d872f056dbe9
  url: https://s3-external-1.amazonaws.com/dpb587-bosh-release-openvpn-us-east-1/artifacts/release/1b77cbd51a3debefcb06f2ad5311d872f056dbe9
  version: 5.0.0
- name: networking
  sha1: 9b5f9d27917c3754e492470ac6c9af80d62963db
  url: http://bosh.io/d/github.com/cloudfoundry/networking-release?v=9
  version: 9
- name: ssoca
  sha1: beae0e18ea00e2f0ebae12abe03e97d49a50bedc
  url: https://s3-external-1.amazonaws.com/dpb587-ssoca-bosh-release-us-east-1/releases/ssoca/ssoca-0.10.0.tgz
  version: 0.10.0
- name: "caddy"
  version: "0.6.0"
  url: "https://bosh.io/d/github.com/dpb587/caddy-bosh-release?v=0.6.0"
  sha1: "27ea56243236ffe26267092fc672c591930cd0e0"

stemcells:
- alias: default
  os: ubuntu-trusty
  version: ((stemcell_version))

update:
  serial: false
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 5000 - 90000
  update_watch_time: 5000 - 90000

instance_groups:
- name: openvpn
  instances: 1
  stemcell: default
  vm_type: openvpn_server
  persistent_disk_type: caddy-ssd
  azs: [us1]
  networks:
  - name: concourse
    default: [dns, gateway]
  - name: vip
    static_ips:
    - ((vpn_server_external_ip))
  jobs:
  - name: bpm
    release: bpm
  - name: ssoca-openvpn-verify
    release: ssoca
    properties: {}
  - name: iptables
    release: networking
    properties:
      iptables:
        nat:
          POSTROUTING:
          - -s ((vpn_network))/((vpn_network_mask_bits)) -d ((bosh_cpi.external_ip))/32 -j MASQUERADE
          - -s ((vpn_network))/((vpn_network_mask_bits)) -d ((bosh_core.external_ip))/32 -j MASQUERADE
  - name: openvpn
    release: openvpn
    properties:
      push_routes:
      - ((bosh_cpi.external_ip)) 255.255.255.255
      - ((bosh_core.external_ip)) 255.255.255.255
      server: ((vpn_network)) ((vpn_network_mask))
      tls_server: ((server_key_pair))
      dh_pem: |
        -----BEGIN DH PARAMETERS-----
        MIIBCAKCAQEA/oih/YXvkf13npOIF5LW170/V5j4R20NjL/IzgdZUYMlsQtm5zMZ
        LwA8Vk1v9UnSWkopAGuJ8gZxz4qKk2p2MLzHSDwXC5khGrrJlHfjn7H0lYilyFqn
        2YhmfCQ7z7ih0jUS/iNf/+xUmfoJn/2OMEY3gmcAxAbtVRqNtGFwsTjtap3Rgbt9
        /j7Xbrsp3JqSeWN3VSqMzAgUrjkkkv52HcDo4zA1KfN7m+ROj/uGxcrmvZr7G0RK
        9yJ2f8I1x8EW3p+CmWhHcmoNyxxlfRHIsZ+82+BIessN99pSxCbjWvhggntFLRwC
        fcrq5wk9ei7dzYjZHSPHqvhmmZgWKJZYQwIBAg==
        -----END DH PARAMETERS-----
      extra_configs:
      - duplicate-cn
      - script-security 2
      - tls-verify "/var/vcap/packages/ssoca-openvpn-verify/bin/tls-verify 2m"
      - tls-export-cert /var/vcap/data/ssoca-openvpn-verify/certs
  - name: ssoca
    release: ssoca
    consumes:
      openvpn:
        network: vip
    properties:
      env:
        name: "bosh"
        title: "BOSH VPN"
        url: "((ssoca_external_url))"
        banner: Unauthorized use is strictly prohibited. All access and activity is subject to logging and monitoring.
        metadata:
          ui.link.Team VPN Docs: https://github.com/pivotal-cf/bosh-concourse-deployments/blob/master/vpn/README.md
          ui.link.Need Help?: https://cloudfoundry.slack.com/messages/C094QMKB2/ # cloudfoundry#bosh-cpi-dev
          ui.usage: |
            # Linux/macOS
            ssoca -e bosh openvpn exec --sudo

            # macOS: if you want to connect via Tunnelblick profile
            ssoca -e bosh openvpn create-tunnelblick-profile --install

            # Windows: use PowerShell as Administrator
            ssoca -e bosh openvpn exec
      auth:
        type: github
        options:
          client_id: ((github_client_id))
          client_secret: ((github_client_secret))
          jwt: ((ssoca_jwt))
      certauths:
      - name: default
        type: memory
        # the openvpn CA's certificate and private_key so we can sign client certificates
        options: ((ca))
      openvpn_service_link:
        require:
        - or: [] # github team in the format ORG/TEAM
  - name: caddy
    release: caddy
    properties: {}

variables:
- name: ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: server_key_pair
  type: certificate
  options:
    ca: ca
    common_name: openvpn
    alternative_names:
    - ((vpn_server_external_ip))
    extended_key_usage:
    - server_auth
- name: ssoca_jwt
  type: rsa
