---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: nimbus-testbed-info

outputs:
  - name: nimbus-vcenter-vars

params:
  VCENTER_PASSWORD:

run:
  path: deployments-src/ci/tasks/create-nimbus-vcenter-vars
