---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: deployments-src
  - name: terraform
  - name: concourse
  - name: garden-runc-release
  - name: windows-utilities
  - name: stemcell
  - name: windows-stemcell
  - name: bosh-cli
  - name: ulimit
  - name: windows-tools

params:
  DEPLOYMENT_NAME:                ""
  DEPLOYMENT_CONFIG_PATH:         ""
  CONCOURSE_SECRETS:              ""
  BOSH_ENVIRONMENT:               ""
  BOSH_CLIENT:                    ""
  BOSH_CLIENT_SECRET:             ""
  BOSH_CA_CERT:                   ""
  JUMPBOX_HOST:                   ""
  JUMPBOX_SSH_USER:               ""
  JUMPBOX_SSH_KEY:                ""
  CONCOURSE_EXTERNAL_URL:         ""
  CONCOURSE_BASIC_AUTH_USERNAME:  ""
  CONCOURSE_BASIC_AUTH_PASSWORD:  ""
  CONCOURSE_GITHUB_CLIENT_ID:     ""
  CONCOURSE_GITHUB_CLIENT_SECRET: ""
  CONCOURSE_TEAMS:                "[]"

run:
  path: deployments-src/ci/tasks/deploy-concourse
