---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: deployments-src
  - name: stemcell
  - name: bosh-cli
  - name: networking-release
  - name: openvpn-release
  - name: caddy-bosh-release
  - name: ssoca
  - name: terraform

params:
  JUMPBOX_SSH_USER:   ""
  JUMPBOX_SSH_KEY:    ""
  BOSH_CLIENT:        ""
  BOSH_CLIENT_SECRET: ""
  BOSH_CA_CERT:       ""
  VPN_SECRETS:        ""
  EXTERNAL_HOST:      ""

run:
  path: deployments-src/ci/tasks/deploy-vpn-server
