---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
  - name: deployments-src
  - name: bosh-cpi-release
  - name: bosh-cli
  - name: concourse
  - name: worker-state
  - name: stemcell
  - name: testbed-info
    optional: true

outputs:
  - name: updated-worker-state

params:
  IAAS_CREDENTIALS: ""
  OPTIONAL_FLAGS:   ""
  WORKER_SECRETS:   ""
  ENVIRONMENT_NAME: ""

run:
  path: deployments-src/ci/tasks/deploy-worker
