---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: devtools-docker-local.artifactory.eng.vmware.com/vmware/nimbus/nimbus-worker

inputs:
- name: deployments-src

params:
  USER: ""
  DAYS: 7
  TESTBED_NAME: ""

run:
  path: deployments-src/ci/tasks/extend-lease-nimbus-testbed
