---
name: concourse-worker

releases:
- name: concourse
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: worker
  instances: 1
  azs: [z1, z2, z3]
  vm_type: large
  stemcell: xenial
  networks:
  - name: default
    default: [dns, gateway]
  - name: public
    static_ips: [10.196.3.90]
  jobs:
  - name: worker
    release: concourse
    properties:
      log_level: debug
      tags: ((worker_tags))
      worker_gateway:
        hosts: ["((bosh_core_concourse_tsa_host))"]
        host_public_key: ((bosh_core_concourse_tsa_host_key.public_key))
        worker_key: ((worker_key))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
