---
name: concourse-cpi

releases:
- name: bpm
  version: ((bpm_version))
- name: caddy
  version: ((caddy_version))
- name: concourse
  version: ((concourse_version))

stemcells:
- alias: default
  os: ubuntu-xenial
  version: ((stemcell_version))

update:
  serial: false
  canaries: 100
  max_in_flight: 100
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000

instance_groups:
- name: concourse_cpi
  instances: 1
  vm_type: concourse_cpi
  persistent_disk_pool: caddy-ssd
  stemcell: default
  azs: [us1]
  networks:
  - name: concourse
    default: [dns, gateway]
  jobs:
  - name: bpm
    release: bpm
  - name: web
    release: concourse
    properties:
      external_url: ((concourse_external_url))
      token_signing_key: ((token_signing_key))
      postgresql:
        host: ((concourse_db_host))
        database: atc
        role:
          name: atc
          password: ((concourse_db_password))
      worker_gateway:
        host_key: ((tsa_host_key))
        token_signing_key: ((token_signing_key))
        authorized_keys: [((worker_key.public_key))]
        team_authorized_keys: {} # these will be added by the team-authorized-public-key ops file
      add_local_users:
      - ((concourse_basic_auth_username)):((concourse_basic_auth_password))
      github_auth:
        client_id: ((concourse_github_client_id))
        client_secret: ((concourse_github_client_secret))
      main_team:
        auth:
          local:
            users: [((concourse_basic_auth_username))]
  - name: caddy
    release: caddy
    properties:
      acme:
        email: ((letsencrypt_registration_email))
      caddyfile: |
        ((concourse_external_host)) {
          gzip

          tls {
            dns route53
          }
          proxy / localhost:8080 {
            transparent
            websocket
          }
        }
      env:
        AWS_ACCESS_KEY_ID: ((route53_aws_access_id))
        AWS_SECRET_ACCESS_KEY: ((route53_aws_secret_access_key))
        AWS_HOSTED_ZONE_ID: ((route53_hosted_zone_id))

- name: shared_worker
  instances: 3
  vm_type: concourse_worker_8_24
  stemcell: default
  azs: [us1]
  networks:
  - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
        host_public_key: ((tsa_host_key.public_key))
      garden:
        allow_host_access: true

- name: asia_worker
  instances: 1
  vm_type: concourse_worker_2_8
  stemcell: default
  azs: [asia]
  networks:
  - name: concourse-asia
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
        host_public_key: ((tsa_host_key.public_key))
      garden:
        allow_host_access: true
      tags: [asia]
      team: pivotal

# worker instances will be added via worker-ops.yml
