---
name: concourse-core

releases:
- name: concourse
  version: ((concourse_version))
- name: garden-runc
  version: ((garden_version))
- name: ulimit
  version: latest
- name: windows-utilities
  version: latest
- name: slack-notification-resource
  version: 9
  url: http://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b
- name: caddy
  version: 0.4.0
  url: https://s3-external-1.amazonaws.com/dpb587-caddy-bosh-release-us-east-1/artifacts/release/e188beda8316131c0b50758fc69ed2eff505e75b
  sha1: e188beda8316131c0b50758fc69ed2eff505e75b
- name: windows-tools
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: ((stemcell_version))
# Windows Stemcell for AWS: https://s3.amazonaws.com/bosh-windows-stemcells/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
- alias: windows
  os: windows2016
  version: latest

update:
  canaries: 1
  max_in_flight: 6
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000
  # vm_strategy: create-swap-delete
  serial: false

instance_groups:
- name: atc
  instances: 1
  vm_type: concourse_core
  persistent_disk_pool: caddy-ssd
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: atc
      release: concourse
      properties:
        external_url: ((concourse_external_url))
        bind_port: 8080
        publicly_viewable: true
        container_placement_strategy: random
        postgresql:
          host: ((database_host))
          database: ((database_name))
          role:
            name: ((database_role))
            password: ((database_password))
        github_auth:
          client_id: ((concourse_github_client_id))
          client_secret: ((concourse_github_client_secret))
        token_signing_key: ((token_signing_key))
        add_local_users:
        - ((concourse_basic_auth_username)):((concourse_basic_auth_password))
        main_team:
          auth:
            local:
              users: [((concourse_basic_auth_username))]
            github:
              teams: ((main_team_github_teams))
    - name: tsa
      release: concourse
      properties:
        authorized_keys: ((tsa_authorized_keys))
        host_key: ((tsa_host_key))
        token_signing_key: ((token_signing_key))
    - name: ulimit
      release: ulimit
      properties:
        nofile:
          soft: 32768
          hard: 32768
    - name: caddy
      release: caddy
      properties:
        acme:
          email: ((letsencrypt_registration_email))
        caddyfile: |
          ((concourse_external_host)) {
            gzip

            tls {
              dns route53
            }
            proxy / localhost:8080 {
              transparent
              websocket
            }
          }
        env:
          AWS_ACCESS_KEY_ID: ((route53_aws_access_id))
          AWS_SECRET_ACCESS_KEY: ((route53_aws_secret_access_key))
          AWS_HOSTED_ZONE_ID: ((route53_hosted_zone_id))

- name: worker
  instances: 16
  vm_type: concourse_core_worker_12_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-default
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: &additional_resource_types
        - type: slack-notification
          image: /var/vcap/packages/slack-notification-resource
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
    - name: garden
      release: garden-runc
      properties: &garden
        garden:
          listen_network: tcp
          listen_address: 127.0.0.1:7777
          allow_host_access: true
          btrfs_store_size_mb: 1000000
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-default
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-brats
  instances: 4
  vm_type: concourse_core_worker_12_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-brats
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - worker-brats
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-brats
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-integration-1
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-1
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-1
        - bosh-integration-db-tls-hotswap # backwards compatibility with branch pipelines
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-1
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker-integration-2
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-2
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-2
        - bosh-integration-db-tls-mysql # backwards compatibility with branch pipelines
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-2
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker-integration-3
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-3
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-3
        - bosh-integration-db-tls-postgres # backwards compatibility with branch pipelines
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-3
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker-integration-4
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-4
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-4
        - bosh-integration-9 # backwards compatibility with branch pipelines
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-4
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker-integration-5
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-5
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - bosh-integration-5
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-5
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker-integration-6
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-integration-6
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
        - bosh-integration
        - fly-integration
        - bosh-integration-6
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-integration-6
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}
  networks:
    - name: concourse

- name: worker-dns-performance
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
    - name: worker
      release: concourse
      consumes:
        baggageclaim:
          from: baggageclaim-worker-dns-performance
      properties:
        tsa:
          worker_key: ((worker_key))
          host_public_key: ((tsa_host_key.public_key))
          registration_mode: forward
        additional_resource_types: *additional_resource_types
        baggageclaim:
          forward_address: 127.0.0.1:7788
        garden:
          forward_address: 127.0.0.1:7777
        tags:
          - dns-performance
    - name: garden
      release: garden-runc
      properties: *garden
    - name: baggageclaim
      release: concourse
      properties:
        driver: btrfs
      provides:
        baggageclaim:
          as: baggageclaim-worker-dns-performance
    - name: slack-notification-resource
      release: slack-notification-resource
      properties: {}

- name: worker-windows
  instances: 1
  stemcell: windows
  vm_type: concourse_core_worker_8_16
  azs: [us1]
  networks:
  - name: concourse-windows
  jobs:
  - name: houdini-windows
    release: concourse
    provides: {garden: {as: windows-garden}}
  - name: baggageclaim-windows
    release: concourse
    provides: {baggageclaim: {as: windows-baggageclaim}}
  - name: worker-windows
    release: concourse
    consumes:
      baggageclaim: {from: windows-baggageclaim}
      garden: {from: windows-garden}
    properties:
      tsa:
        worker_key: ((worker_key))
        host_public_key: ((tsa_host_key.public_key))
        registration_mode: forward
  - name: set_password
    release: windows-utilities
    properties:
      set_password:
        username: "((windows_administrator_username))"
        password: "((windows_administrator_password))"
  - name: enable_ssh
    release: windows-utilities
  - name: golang-windows
    release: windows-tools
  - name: ginkgo
    release: windows-tools
  - name: mingw64
    release: windows-tools
