---
name: concourse-cpi

releases:
- name: bpm
  version: ((bpm_version))
- name: caddy
  version: ((caddy_version))
- name: concourse
  version: ((concourse_version))

stemcells:
- alias: default
  os: ubuntu-xenial
  version: ((stemcell_version))

update:
  serial: false
  canaries: 100
  max_in_flight: 100
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000

instance_groups:
- name: concourse_cpi
  instances: 1
  vm_type: concourse_cpi
  stemcell: default
  azs: [us1]
  networks:
  - name: concourse
    default: [dns, gateway]
  jobs:
    - name: web
      release: concourse
      properties:
        external_url: ((concourse_external_url))
        token_signing_key: ((token_signing_key))
        postgresql:
          host: ((concourse_db_host))
          database: atc
          role:
            name: atc
            password: ((concourse_db_password))
        worker_gateway:
          host_key: ((tsa_host_key))
          token_signing_key: ((token_signing_key))
          authorized_keys: [((worker_key.public_key))]
          team_authorized_keys: [] # keys will be added via worker-ops.yml
        add_local_users:
        - ((concourse_basic_auth_username)):((concourse_basic_auth_password))
        github_auth:
          client_id: ((concourse_github_client_id))
          client_secret: ((concourse_github_client_secret))
        main_team:
          auth:
            local:
              users: [((concourse_basic_auth_username))]
        tls_cert: ((tls_cert))
        tls_key: ((tls_key))

- name: shared_worker
  instances: 3
  vm_type: concourse_worker_8_24
  stemcell: default
  azs: [us1]
  networks:
  - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
        host_public_key: ((tsa_host_key.public_key))
      garden:
        allow_host_access: true

- name: asia_worker
  instances: 1
  vm_type: concourse_worker_2_8
  stemcell: default
  azs: [asia]
  networks:
  - name: concourse-asia
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
        host_public_key: ((tsa_host_key.public_key))
      garden:
        allow_host_access: true
      tags: [asia]
      team: pivotal

# worker instances will be added via worker-ops.yml
