---
name: concourse-core

releases:
- name: bpm
  version: ((bpm_version))
- name: caddy
  version: ((caddy_version))
- name: concourse
  version: ((concourse_version))
- name: windows-tools
  version: ((windows_tools_version))
- name: windows-utilities
  version: ((windows_utilities_version))

stemcells:
- alias: default
  os: ubuntu-xenial
  version: ((stemcell_version))
# Windows Stemcell for AWS: https://s3.amazonaws.com/bosh-windows-stemcells/light-bosh-stemcell-*-aws-xen-hvm-windows2012R2-go_agent.tgz
- alias: windows
  os: windows2016
  version: latest

update:
  canaries: 1
  max_in_flight: 6
  canary_watch_time: 30000 - 90000
  update_watch_time: 30000 - 90000
  serial: false

instance_groups:
- name: web
  instances: 1
  vm_type: concourse_core
  persistent_disk_type: caddy-ssd
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: bpm
    release: bpm
  - name: web
    release: concourse
    properties:
      external_url: ((concourse_external_url))
      token_signing_key: ((token_signing_key))
      postgresql:
        host: ((database_host))
        database: ((database_name))
        role:
          name: ((database_role))
          password: ((database_password))
      worker_gateway:
        host_key: ((tsa_host_key))
        authorized_keys: ((tsa_authorized_keys))
      container_placement_strategy: fewest-build-containers
      github_auth:
        client_id: ((concourse_github_client_id))
        client_secret: ((concourse_github_client_secret))
      add_local_users:
      - ((concourse_basic_auth_username)):((concourse_basic_auth_password))
      main_team:
        auth:
          local:
            users: [((concourse_basic_auth_username))]
          github:
            teams: ((main_team_owner_github_teams))
  - name: caddy
    release: caddy
    properties:
      acme:
        email: ((letsencrypt_registration_email))
      caddyfile: |
        ((concourse_external_host)) {
          gzip

          tls {
            dns route53
          }
          proxy / localhost:8080 {
            transparent
            websocket
          }
        }
      env:
        AWS_ACCESS_KEY_ID: ((route53_aws_access_id))
        AWS_SECRET_ACCESS_KEY: ((route53_aws_secret_access_key))
        AWS_HOSTED_ZONE_ID: ((route53_hosted_zone_id))

- name: worker
  instances: 16
  vm_type: concourse_core_worker_12_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true

- name: worker-brats
  instances: 4
  vm_type: concourse_core_worker_12_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - worker-brats

- name: worker-integration-1
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - bosh-integration
      - bosh-integration-1
      - bosh-integration-db-tls-hotswap # backwards compatibility with branch pipelines

- name: worker-integration-2
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - bosh-integration
      - bosh-integration-2
      - bosh-integration-db-tls-mysql # backwards compatibility with branch pipelines

- name: worker-integration-3
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - bosh-integration
      - bosh-integration-3
      - bosh-integration-db-tls-postgres # backwards compatibility with branch pipelines

- name: worker-integration-4
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - bosh-integration
      - bosh-integration-4
      - bosh-integration-9 # backwards compatibility with branch pipelines

- name: worker-integration-5
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - bosh-integration
      - bosh-integration-5

- name: worker-integration-6
  instances: 1
  vm_type: concourse_core_worker_32_64
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - bosh-integration
      - fly-integration
      - bosh-integration-6

- name: worker-dns-performance
  instances: 1
  vm_type: concourse_core_worker_8_16
  stemcell: default
  azs: [us1]
  networks:
    - name: concourse
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - dns-performance

- name: worker-windows
  instances: 1
  stemcell: windows
  vm_type: concourse_core_worker_8_16
  azs: [us1]
  networks:
  - name: concourse-windows
  jobs:
  - name: worker-windows
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
  - name: set_password
    release: windows-utilities
    properties:
      set_password:
        username: "((windows_administrator_username))"
        password: "((windows_administrator_password))"
  - name: enable_ssh
    release: windows-utilities
  - name: golang-windows
    release: windows-tools
  - name: ginkgo
    release: windows-tools
  - name: mingw64
    release: windows-tools

- name: worker-asia
  instances: 1
  vm_type: concourse_core_worker_2_8
  stemcell: default
  azs: [asia]
  networks:
  - name: concourse-asia
  jobs:
  - name: worker
    release: concourse
    properties:
      worker_gateway:
        worker_key: ((worker_key))
      garden:
        allow_host_access: true
      tags:
      - asia
      team: pcf
