---
jobs:
- name: renew-lease-nimbus-testbed
  plan:
  - do:
    - in_parallel:
      - get: deployments-src
      - get: every-day
        trigger: true
    - task: extend-lease
      file: deployments-src/ci/tasks/extend-lease-nimbus-testbed.yml
      params:
        TESTBED_NAME: bosh-main-ci
        USER: ((nimbus-user))

- name: create-nimbus-testbed
  plan:
  - do:
    - in_parallel:
      - get: deployments-src
    - put: nimbus-worker
      params:
        template: default
        output: nimbus-worker
        run:
          path: bash
          args:
            - -exc
            - |
              export USER=((nimbus-user))
              export TESTBED_NAME=bosh-main-ci
              /mts/git/bin/nimbus-ctl --testbed kill ${TESTBED_NAME} || true
              /mts/git/bin/nimbus-testbeddeploy \
                  --testbedSpecRubyFile deployments-src/nimbus-testbed/nimbus_vc70_dual_networks.rb \
                  --runName ${TESTBED_NAME} \
                  --lease 7 \
                  --enableIPV6 dual \
                  --ip6AddressType slaac \
                  --context general:nsx \
                  --nimbusLocation wdc \
                  --resultsDir nimbus-worker
              echo "{}" > nimbus-worker/clean-env
      ensure:
        do:
        - put: testbed-info
          params:
            file: nimbus-worker/testbedInfo.json
        - put: vsphere-v7.0-worker-state-1
          params:
            file: nimbus-worker/clean-env
        - put: vsphere-v7.0-worker-state-2
          params:
            file: nimbus-worker/clean-env

- name: update-vsphere-v7.0-worker
  serial: true
  plan:
    - do:
      - in_parallel:
        - get: concourse
        - get: deployments-src
        - get: bosh-cli
        - get: testbed-info
          trigger: true
        - get: vsphere-v7.0-worker-state-1
        - get: vsphere-v7.0-worker-state-2
        - get: bosh-cpi-release
          resource: bosh-vsphere-cpi-release
        - get: stemcell
          resource: vsphere-xenial-stemcell
      - in_parallel:
        - task: update-vsphere-v7.0-worker-1
          file: deployments-src/ci/tasks/deploy-worker.yml
          input_mapping:
            worker-state: vsphere-v7.0-worker-state-1
          params:
            WORKER_SECRETS: ((vsphere-v70-worker-secrets-1))
            ENVIRONMENT_NAME: nimbus
          ensure:
            put: vsphere-v7.0-worker-state-1
            params:
              file: updated-worker-state/worker-state.json
        - task: update-vsphere-v7.0-worker-2
          file: deployments-src/ci/tasks/deploy-worker.yml
          input_mapping:
            worker-state: vsphere-v7.0-worker-state-2
          params:
            WORKER_SECRETS: ((vsphere-v70-worker-secrets-2))
            ENVIRONMENT_NAME: nimbus
          ensure:
            put: vsphere-v7.0-worker-state-2
            params:
              file: updated-worker-state/worker-state.json

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: nimbus-worker
  type: registry-image
  source:
    repository: devtools-docker-local.artifactory.eng.vmware.com/vmware/runway/resourcetypes/nimbus-worker-resource
    tag: latest

resources:
- name: every-day
  type: time
  source:
    interval: 24h
- name: deployments-src
  type: git
  source:
    uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
    branch: master
- name: testbed-info
  type: gcs-resource
  source:
    bucket: ((deployments_core_bucket_name))
    json_key: ((gcp_credentials_json))
    versioned_file: nimbus/testbed-info.json

- name: vsphere-v7.0-worker-state-1
  type: gcs-resource
  source:
    bucket: ((deployments_core_bucket_name))
    json_key: ((gcp_credentials_json))
    versioned_file: worker/vsphere-v7.0-worker-state-1.json
- name: vsphere-v7.0-worker-state-2
  type: gcs-resource
  source:
    bucket: ((deployments_core_bucket_name))
    json_key: ((gcp_credentials_json))
    versioned_file: worker/vsphere-v7.0-worker-state-2.json
- name: bosh-cli
  type: s3
  source:
    bucket: bosh-cli-artifacts
    regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64
- name: vsphere-xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-xenial-go_agent
- name: concourse
  type: bosh-io-release
  source:
    repository: concourse/concourse-bosh-release
- name: bosh-vsphere-cpi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh-vsphere-cpi-release
- name: nimbus-worker
  type: nimbus-worker
  icon: worker
  source:
    nimbus_user: ((nimbus-user))
    # wdc Wenatchee, Washington closest to us-west1 (The Dalles, Oregon) which is where bosh main concourse lives
    # https://confluence.eng.vmware.com/display/DevToolsDocKB/Nimbus+CIDR
    nimbus_location: wdc
