---
jobs:
- name: renew-lease-nimbus-testbed
  plan:
  - do:
    - in_parallel:
      - get: deployments-src
      - get: every-day
        trigger: true
    - task: extend-lease
      file: deployments-src/ci/tasks/extend-lease-nimbus-testbed.yml
      params:
        TESTBED_NAME: bosh-main-ci
        USER: rkoster # TODO change to service account

- name: create-nimbus-testbed
  plan:
  - do:
    - in_parallel:
      - get: deployments-src
    - task: testbed-deploy
      file: deployments-src/ci/tasks/deploy-nimbus-testbed.yml
      params:
        TESTBED_NAME: bosh-main-ci
        USER: rkoster # TODO change to service account
      ensure:
        put: testbed-info
        params:
          file: nimbus-testbed-info/testbedInfo.json

resources:
  - name: deployments-src
    type: git
    source:
      uri: https://github.com/pivotal-cf/bosh-concourse-deployments.git
- name: every-day
  type: time
  source:
    interval: 24h

  - name: testbed-info
    type: gcs-resource
    source:
      bucket: {{deployments_core_bucket_name}}
      json_key: {{gcp_credentials_json}}
      versioned_file: nimbus/testbed-info.json
